### PR TITLE
bump consul to 1.0.6 and switch to hcl config file format

### PR DESCRIPTION
**Pull request by fulminemizzega**
Hello,
this PR updates consul to 1.0.6 and changes consul configuration file from json to hcl. The main reason I made this change is because hcl supports comments.
I pushed more changes to my master branch, if I submit another PR do you think you would merge those?

### CODE REVIEW

**Comment by duritong** [comment]
I like, though: How are existing setups affected by the switch to the hcl format?

**Comment by fulminemizzega** [comment]
I read from here https://www.consul.io/docs/agent/options.html#_hcl that hcl format is supported since consul 1.0.
The new config file has the same defaults as your json version, everything else is commented out. Consul is able to find by itself if a file is in hcl format or json format. I don't know if there is an issue mixing both hcl and json config files in /etc/consul.d.

**Comment by duritong** [comment]
So what happens if someone has a config.json and then we place the hcl there? which one is preferred? Will it break?

**Comment by fulminemizzega** [comment]
https://www.consul.io/docs/agent/options.html, paragraph that begins with "When loading configuration", consul takes config files in alphabetical order. I made a test, I put consul.hcl and consul.json in /etc/consul.d,
#### consul.hcl:
```hcl
# Run agent in server mode
server = true

data_dir = "/var/lib/consul"
log_level = "INFO"
datacenter = "dc2"
```
#### consul.json
```json
{
	"server": false
}
```
then started consul with
```bash
consul agent -config-dir=/etc/consul.d/ -bind=172.17.0.1 -dev
```
And this is what consul prints:
```
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v1.0.6'
           Node ID: '3d8164ac-3394-85f3-9b02-aaf8555d1a90'
         Node name: 'f27vm'
        Datacenter: 'dc2' (Segment: '')
            Server: false (Bootstrap: false)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, DNS: 8600)
      Cluster Addr: 172.17.0.1 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false
```
As you can see, consul.json overrides consul.hcl because it comes after it in alphabetical (lexical?) order (Server is false in output).
So yes, it will break if rpm installs a file named consul.hcl in /etc/consul.d, but in this PR I decided to keep -dist at the end of config files (as you have done before), consul will ignore it (config files have to end in .hcl or .json). The version in my repository of this rpm does install a file consul.hcl if it does not exist already.

**Comment by duritong** [comment]
Superseeded by #74 - still thanks and sorry for not getting it merged. Would you mind updating the hcl branch to the latest version? Thanks!

**Pull request closed without merging**
