### PR TITLE
Various improvements to the package

### PR DESCRIPTION
**Pull request by duritong**
This PR is a successor of #5, but also addresses various other PR, such as #7 and #6 . Furthermore it also addresses concerns in #4.

Changelog is as followed:

* update to 0.5.0
* fix SysV init on restart
* added webui subpackage
* include statedir in package
* run as unprivileged user
* protect deployed configs from overwrites

I will comment on the other PRs and point to that PR.

To finish I'd like to add, that I'm totally fine to just submit PRs, however if you don't want to maintain the repository anymore, I'm more than happy to take things over.

### CODE REVIEW

**Comment by phrawzty** [comment]
> To finish I'd like to add, that I'm totally fine to just submit PRs, however if you don't want to maintain the repository anymore, I'm more than happy to take things over.

Hi @duritong,

You may be interested in [my fork](https://github.com/phrawzty/consul-rpm) which incorporates most of these changes.  More importantly, since it would appear that there is a small community of us now, I propose that we set up our own repository based on @tomhillable's work and move forward from there as a maintained project.  We could set it up as a shared-pushable repo under one of our accounts, or form a small organisation - thoughts?

**Comment by tomhillable** [comment]
@duritong, @phrawzty - Thanks for the PRs, looking great. Sorry for the delay on my part!
Just added you both as collaborators to the repo :)

**Comment by duritong** [comment]
@tomhillable sounds great, thanks a lot!

@phrawzty do you like to see how to incorporate your changes and make a PR on this repo where we can discuss next steps?

**Comment by phrawzty** [comment]
@duritong I am currently reviewing the differences between the current repo and my fork; there's a bunch of little things, but the biggest difference is that the current spec build a separate package for the UI, whereas mine just bundled the two together.  There's an argument to be made either way, but I'm not going to debate it - two packages is fine. :grinning:  I think there's a handful of small modifications to be made for which I'll propose a PR shortly.

**Comment by phrawzty** [comment]
View PR #9.

**Comment by arodd** [comment]
Thanks Guys!

**Pull request merged**
