### PR TITLE
Configs into consul.d and consul-template.d

### PR DESCRIPTION
**Pull request by mmraz**
The consul.io documentation refers to /etc/consul.d and /etc/consul-template.d for configuration files. See https://www.consul.io/intro/getting-started/services.html as an example.  The public consul Chef cookbook and several other configuration management tools also utilize this path when setting up configurations.

This PR is to create the consul, consul-ui and consul-template RPMs to be consistent with this configuration path pattern.

Also bumped the default consul and consul-ui version to 0.7.1.

### CODE REVIEW

**Comment by mmraz** [comment]
The merge and merge revert are adding and removing the bento URL from the Vagrant file.

**Comment by duritong** [comment]
Main main question would be: How do we keep backward compatibility? By just merging these changes we would break any existing installation, which is probably not what you expect through a minor version upgrade. Don't get me wrong: I'm not against moving things to standard locations, BUT we can't just change and break all the existing installations.

Also you could squash some of the commits, so we would get one for the version upgrade and all the .d changes.

Btw: you can also change the sysconfig files through chef and then keep the rest to the standard.

**Comment by mmraz** [comment]
https://www.consul.io/docs/agent/options.html states that -config-dir can be specified multiple times.  Would having both /etc/consul and /etc/consul.d entries in the sysconfig file take care of backwards compatibility?

**Comment by mmraz** [comment]
I rebased, squashed, pulled out the merge and revert, added the backwards compatibility entries for consul.sysconfig and consul-template.sysconfig

**Comment by duritong** [comment]
Ok, I would be fine with the change and I fixed the conflict I introduced. What does @tomhillable, @phrawzty or @rumenvasilev think?

**Comment by phrawzty** [comment]
The diff looks fine. 👍

We should probably think about how long we want to support the "backwards compatibility" - that's the sort of thing that comes back to bite you later.

**Comment by duritong** [comment]
so let's make this happen. Thanks a lot for the proposal and the work on it.

**Pull request merged**
